import type { NextPage } from "next";
import Head from "next/head";

import {
	Box,
	Button,
	chakra,
	Container,
	Flex,
	Grid,
	GridItem,
	Heading,
	Image,
	SimpleGrid,
	Stack,
	Tab,
	TabList,
	TabPanel,
	TabPanels,
	Tabs,
	Text,
} from "@chakra-ui/react";
import HomepageCard from "../components/cards/HomepageCard";
import ThemeSort from "../components/homepage/ThemeSort";
import NavBar from "../components/layouts/Navigation";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Home | CSDT</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<NavBar />

			<Container as={"main"} maxW={"6xl"}>
				<Tabs variant="soft-rounded" colorScheme="blue">
					<Flex
						justifyContent={"space-between"}
						mt={5}
						align={"center"}
						direction={{ base: "column-reverse", md: "row" }}>
						<Box>
							<Heading>Applications</Heading>
							<Heading fontWeight={"300"} size={"lg"} mt={5}>
								Theme
							</Heading>
							<TabList>
								<Tab>Computing</Tab>
								<Tab>Culture</Tab>
								<Tab>Mathematics</Tab>
								<Tab>Biology</Tab>
							</TabList>
						</Box>

						<Box
							className="rounded-lg shadow-md dark:bg-gray-100"
							maxW={"450px"}
							p={5}
							color={"gray.500"}
							borderColor={"gray.500"}
							border={"1px solid"}>
							<Text>
								The elitist myths of "savages" and "white trash" led to today's bigotry. Here you can counter those
								stereotypes with African fractals, Appalachian quilting algorithms and more. From Native beadwork to
								urban graffiti, students can find the “heritage algorithms” of their interest, learn their connection to
								STEM principles, and develop designs of their own creation.
							</Text>

							<Text>Learn, create, and share your work with Culturally Situated Design Tools!!</Text>
						</Box>
					</Flex>

					<TabPanels>
						<TabPanel>
							<Heading fontSize={"1.5rem"}>
								Discrete Iteration:{" "}
								<chakra.span fontSize={"1rem"} fontWeight={"500"}>
									Many cultural patterns are just repeating shapes. Great for beginners!
								</chakra.span>
							</Heading>
							<div className="grid grid-cols-1 gap-y-10 gap-x-6 sm:grid-cols-3 lg:grid-cols-5 xl:grid-cols-6 xl:gap-x-8">
								<HomepageCard
									name="Quilting"
									link="/quilting"
									image={"/homepage/quilting.jpg"}
									alt=" A virtual representation of an Appalachian Hex Quilt"
								/>
							</div>
						</TabPanel>
						<TabPanel>
							<Heading fontSize={"1.5rem"}>Across Cultures</Heading>
						</TabPanel>
						<TabPanel>
							<Heading fontSize={"1.5rem"}>Transformational Geometry</Heading>
						</TabPanel>
						<TabPanel>
							<Heading fontSize={"1.5rem"}>Biology</Heading>
						</TabPanel>
					</TabPanels>
				</Tabs>
			</Container>
		</div>
	);
};

export default Home;
